### ISSUE TITLE
Feature Request: Add retry for a 2xx response

### ISSUE THREAD

**Issue by jrichardsz** [softonic/axios-retry#100]
In case of  non-RESTful API that can return 200 a json body says otherwise, it would be grateful add a custom function like:

    function retryConditionOnSuccess(successObject) {

**original question**
https://stackoverflow.com/a/59508176/3957754

**my current fix**
https://gist.github.com/jrichardsz/03682d84ad5252d46e209652edd7f401

**Comment by mawrkus** [comment]
Hi!
Please have a look at https://github.com/softonic/axios-retry/pull/88

**Comment by xyclos** [comment]
it is not always the case that a "a poorly-written API" would cause this situation. For example a graphql endpoint could respond with a 200 with an error object in the response body. I too think this would be a nice feature to have.

**Comment by blbradley** [comment]
@mawrkus Please reconsider allowing this; we can't control every API we interact with.

**Comment by dlholt** [comment]
@blbradley @jrichardsz I am consuming an API from Salesforce Marketing Cloud that returns HTTP-200 even if there is an error. I started using **axios** and **axios-retry** today and found this solution:

In the **axios** options, set `validateStatus(status)` ([reference](https://github.com/axios/axios/blob/fd57956a7eadf13fd8006bd53e5065590e9812c4/lib/defaults.js#L79)) to a function that will either return `false` for all status codes, only HTTP-200, or some combination. Then, in the **axios-retry** options, specify a function for `retryCondition(error)` ([reference](https://github.com/softonic/axios-retry/blob/878529a625c721e1d14faa6b6ebdf87f13492949/index.d.ts#L46)) that will inspect the response body (`error.response.data`) and return `true` (retry) or `false` (don't retry) based on the inspection.

Hope that helps!

**Comment by rgalanakis** [comment]
There are totally valid reasons a well-written API would return a success code and you'd want to retry, like polling for a finished job. Success responses (like 202) are much nicer than an ambiguous error response.

Thanks for the workaround @dlholt!

**Comment by hsouna** [comment]
Exactly as @rgalanakis said I'm working with an API that returns 202 if the job is not finished yet! So I think it should be a good idea to add this functionality!

**Comment by ledniy** [comment]
Workaround with interceptor and custom error
```js
const axios = require("axios").default;
const axiosRetry = require("axios-retry").default;

axios.interceptors.response.use(async (response) => {
  if (response.status == 200) {
    const err = new Error("I want to retry");
    err.config = response.config; // axios-retry using this
    throw err;
  }
  return response;
});

axiosRetry(axios, {
  retries: 1,
  retryCondition: (error) => {
    console.log("retryCondition");
    return false;
  },
});

axios
  .get("https://example.com/")
  .catch((err) => console.log(err.message)); // gonna be here anyway as we'll fail due to interceptor logic

```

**Comment by mindhells** [comment]
As there are different workarounds for this explained in this thread, and in agreement with the discussion in #88, we won't make this part of the responsibility of the library, thus I'm closing this issue.
Thanks everyone for your contributions.
