### ISSUE TITLE
Failed request going to continuous loop Instead of specified retry count in my reactjs project 

### ISSUE THREAD

**Issue by julurivinay** [softonic/axios-retry#110]
I have installed axios-retry in my reactjs project.
When api got failed it is looping continuously instead of specified count.

Code is below:

import axios from 'axios';
import axiosRetry from 'axios-retry';

axiosRetry(axios, { retries: 3 });
const httpService = <T>(request: { url: string, method?: Method, config?: {} }, payload: any):
    Promise<{ data?: T, error?: any }> => {
    return new Promise(resolve => {
        axios(request.url, {
            method: request.method ? request.method : 'get',
            data: (request.method === 'post' || request.method === 'put') ? payload : null,
            params: (request.method !== 'post' && request.method !== 'put') ? payload : null,
            ...request.config
        })
            .then(response => {
                resolve({ data: response.data });
            })
            .catch(reason => {
                resolve({ error: reason });
            });
    });
};
export default httpService;

![image](https://user-images.githubusercontent.com/10845809/74538761-e3797a80-4f62-11ea-823a-4bb177b5cb11.png)

**Comment by mawrkus** [comment]
Can you provide more info about the error?

**Comment by martell2010** [comment]
Hi, I haved this problem too, update to "axios-retry": "^3.1.2" fixed for me.

**Comment by Floriferous** [comment]
This is still happening for us with axios 0.19.2 and axios-retry 3.1.2. Will try to revert to axios 0.18.x

**Comment by mawrkus** [comment]
Two suggestions:

- providing more information about the error
- upgrading to the latest versions of both libs

I'll close this issue. But please, feel free to open a new one once you've had the chance to try the suggestions above.
