### ISSUE TITLE
Incomplete type for retryCondition

### ISSUE THREAD

**Issue by karlismelderis** [softonic/axios-retry#136]
I think we're missing bit in retryCondition type

error argument is not pure `axios.AxiosError` axios-retry actually is adding one more property to it:
```TS
config: {
'axios-retry': { retryCount: 0, lastRequestTime: 1111 },
}
```

can you please extend the type?

I tried to add this bit to your index.d.ts and it solved the case for me:
```TS
declare module 'axios' {
  interface AxiosRequestConfig {
    'axios-retry': {
      retryCount: number
      lastRequestTime: number
    }
  }
}
```

**Comment by Jokero** [comment]
@karlismelderis Why do you need `retryCount` and `lastRequestTime` fields there? I guess this should be enough:
```ts
declare module 'axios' {
    export interface AxiosRequestConfig {
        'axios-retry'?: IAxiosRetryConfig;
    }
}
```
Where `IAxiosRetryConfig` is this https://github.com/softonic/axios-retry/blob/v3.1.8/index.d.ts#L25-L53
