### ISSUE TITLE
Why the library doesn't work with POST method?

### ISSUE THREAD

**Issue by iamjinme** [softonic/axios-retry#146]
I'm trying use retry with POST method, but it's fail.

I was look into the souce code and the line 19 doesn't include that, something reason?

`const IDEMPOTENT_HTTP_METHODS = SAFE_HTTP_METHODS.concat(['put', 'delete']);`

**Comment by rahpuser** [comment]
well, I think it is because POST is not idempotent. So this is the list by default. But you can override that.

**Comment by Jokero** [comment]
Sounds strange, I agree. If POST request returns 500, why it shouldn't be retried?

**Comment by rahpuser** [comment]
I think the author opt for the safer approach, following rest patterns and practices, idempotent methods should not change server state or have side effects, so usually idempotent methods are safe and are intended to be safe and called several times having the same result if it is the same request. In the other side POST is not idempotent and usually calling post would have different results even if we use identical requests, that being said, if for your current application is necessary to retry the POST, you can override the list of verbs that are retried by the library, for this you can use the `retryCondition` key, which is a function, in this case you can use `() => true`, which will retry all the request errors ( all post verbs and messages ), or the better approach if you only need to retry the POST errors with an exact code ( for example 422 ) you can create a function and validates the exact escenario..

**Comment by Jokero** [comment]
@rahpuser Yeah, I generally agree with you
