### ISSUE TITLE
TS2339: Property 'retryCount' does not exist on type 'IAxiosRetryConfig'.

### ISSUE THREAD

**Issue by bennycode** [softonic/axios-retry#167]
I am using `axios-retry` with TypeScript and noticed that the [index.d.ts](https://github.com/softonic/axios-retry/blob/v3.1.9/index.d.ts) file does not include all properties of `axios-retry`.

Here is the code that I've tested:

```ts
(error as AxiosError).config['axios-retry'].retryCount
``` 

The `retryCount` is not listed in `index.d.ts` but when logging `error.config['axios-retry']` in pure JavaScript, it shows up:

```json
{
  "lastRequestTime": 1619513340652,
  "retries": 2,
  "retryCount": 2
}
```

**Comment by mindhells** [comment]
retryCount is internal state of a particular request, I believe that's the reason it's not defined in the type

**Comment by YuliyaNovik** [comment]
just in case someone needs this - property 'retryCount' exists on type 'IAxiosRetryConfigExtended' now
