### ISSUE TITLE
Axios error swallowed by axios-retry when performing multipart/form-data uploads

### ISSUE THREAD

**Issue by seanohollaren** [softonic/axios-retry#170]
Hi there,

I have an app where I'm performing multipart/form-data POST uploads with `axios` and `form-data`, as outlined in their docs, in combination with `axios-retry`.  I recently had an issue where uploads were timing out and I tracked it down to requests which were attempting to upload a request body larger than the axios default limit of 10mb.  Normally, axios throws an error immediately reading `ERR_FR_MAX_BODY_LENGTH_EXCEEDED - Request body larger than maxBodyLength limit`, but that didn't happen here.

Instead, it looks like when using `axios-retry` and performing a multipart/form-data upload with a post body that's too large, `axios-retry` swallows the error and instead exhausts its retries and timeouts and reports that the request failed due to the timeout being exceeded, with no mention of the fact that it failed due to an internal axios error.

Is this behavior intended?  It ended up leading to a lot of extra time spent debugging since the root error was not bubbled up and this seems like an issue.

I've created an example which can be run to demonstrate the behavior.  By default it will attempt to perform a POST with `axios-retry` enabled.  To disable it and see the normal behavior, set the number of retries to 0.  When retries are disabled, the behavior functions as expected and the `ERR_FR_MAX_BODY_LENGTH_EXCEEDED` error is immediately thrown.

axios: 0.21.1
axios-retry: 3.1.9

```javascript
const axios = require('axios');
const retry = require('axios-retry');
const FormData = require('form-data');

retry(axios, { retries: 1 });

async function upload() {
  try {
    const form = new FormData();

    // simulate large image and append it to request
    const file = Buffer.alloc(10600000);
    form.append('file', file, { filename: 'exampleFile.png' });

    // post to server
    const response = await axios.post('https://postman-echo.com/post', form, {
      headers: form.getHeaders(),
      timeout: 4000
    });

    return response.data;
  } catch (e) {
    console.log('Caught error: ', e.message);
  }
}

upload();
```

**Comment by idanudel** [comment]
@seanohollaren did you find a solution for this one?
I got the same issue

**Comment by seanohollaren** [comment]
I never found a resolution for axios-retry not throwing an error and I still believe it's likely an issue with the module.  For fixing the underlying error that was causing axios to throw, I fixed it by setting `maxBodyLength` manually.

**Comment by phattranky** [comment]
@idanudel @seanohollaren 

If you read the source code of this repo. You can see it doesn't support the method `POST` by default. You have to use the custom retryCondition like the below code

```
const REQUEST_RETRY_TIMES = 3;
export const axiosRetryClient = axios.create();

// Please note this instance will retry any request methods.
// In some cases retry the POST request is not safe. Consider before use it.
axiosRetry(axiosRetryClient, {
  retries: REQUEST_RETRY_TIMES,
  retryDelay: axiosRetry.exponentialDelay,
  retryCondition: (error: AxiosError) => {
    return (
      (error.code !== 'ECONNABORTED' &&
        (!error.response ||
          (error.response.status >= 500 && error.response.status <= 599) ||
          error.response.status === 0)) ||
      error.code === 'ECONNREFUSED'
    );
  }
});
```

![Screen Shot 2022-03-30 at 12 09 49 PM](https://user-images.githubusercontent.com/6443154/160755674-78baeb08-c78f-4f05-b417-6389242e143e.png)

**Comment by phattranky** [comment]
Here is the default retryCondition from `axios-retry` source code

![33index js — report-html 2022-03-30 12-13-32](https://user-images.githubusercontent.com/6443154/160756155-b4066673-9bbc-42c7-95fb-077c5eb38c04.png)
