### ISSUE TITLE
Allow retrying on specified non-error responses

### ISSUE THREAD

**Issue by haltman-at** [softonic/axios-retry#171]
Hi,

So, some web APIs will unfortunately not return an error as an HTTP error, but will instead give you a 200 OK and then put an error indicator in the response body.  I would like to be able to specify a condition to detect these error responses and retry on them.

Right now, this is impossible; only axios errors are passed to the `retryCondition`.  OK responses are simply assumed to not require a retry.

So, I would suggest adding another function (say, `okRetryCondition`) that OK responses would be passed to.  Obviously, it would default to always false.  But it would also be possible to supply a custom function for it, so that specified OK responses would nonetheless be retried.

As an example, I would like to use axios-retry in the [`@truffle/source-fetcher`](https://github.com/trufflesuite/truffle/tree/develop/packages/source-fetcher) package.  Currently, it uses its own custom retry logic, which is not very good; I would prefer to be able to simply rely on axios-retry.  However, [`etherscan.ts`](https://github.com/trufflesuite/truffle/blob/develop/packages/source-fetcher/lib/etherscan.ts#L79) in this package interfaces with the Etherscan web API, and this API will, on error, still give you a 200 OK, but instead indicate an error in the body (specifically, in the `status` field of the JSON response).  So, I cannot use axios-retry for these purposes, not unless I layer my own retry logic on top of it, which I obviously don't want to do.

Thank you!

**Comment by say8425** [comment]
https://github.com/softonic/axios-retry/issues/100#issuecomment-627626160
