### ISSUE TITLE
Wrong TS type for axios-retry with interceptor config

### ISSUE THREAD

**Issue by loun4** [softonic/axios-retry#175]
`axios-retry` does not have the correct type from interceptor config.

![screenshot2](https://user-images.githubusercontent.com/1511512/134147344-35d39825-0991-4401-b55d-957f4634d3d7.png)

![screenshot](https://user-images.githubusercontent.com/1511512/134146557-43fbeb88-d655-47ae-88b4-983919389a2d.png)

**Comment by amiram** [comment]
Axios 0.24.0
axios-retry 3.2.4

**Comment by mindhells** [comment]
I believe it's not defined in the type because it's the internal state of a particular request.
