### ISSUE TITLE
Supporting Retries after Receiving 202 Status

### ISSUE THREAD

**Issue by 1toddlewis** [softonic/axios-retry#191]
Enhancement request:

axios-retry was written to retry failed requests. However, its internal code is also very useful for dealing with 202 responses for the delayed generation of API data. Since axios-retry is creating request and response interceptors with null functions for successful requests, and because axios itself controls the determination of success vs. failure, axios-retry can never be used to submit a new request after receiving 202.

Is there any interest in expanding the role of axios-retry to include this "successful request" scenario?

**Comment by Rey-Wang** [comment]
plus 1, even support for 200 request

**Comment by mindhells** [comment]
https://github.com/softonic/axios-retry/issues/100#issuecomment-627626160

**Comment by ledniy** [comment]
Workaround with interceptor and custom error:
```
axios.interceptors.response.use(async (response) => {
  // workaround as axios-retry only works with errors
  if (response.status == 202 && response.data.pending) {
    const err = new Error('Pending response');
    err.config = response.config;
    throw err;
  }
  return response;
});
```

**Comment by 1toddlewis** [comment]
Interesting. I ended up solving this problem by also implementing interceptors, but I didn't think about using them to throw a custom error that axios-retry would then process. Nice approach!
