### ISSUE TITLE
retryCondition calling a healthcheck api

### ISSUE THREAD

**Issue by dstone1983** [softonic/axios-retry#194]
Hello All,

I am implementing retry logic to my system. I am attempting to only retry if the health check api comes back successful. It seems to be retrying no matter what.

doing a:

`retryCondition:() => false`

works

`retryCondition: async () => {
  try {
    await axios.get(healthcheckurl)
    return true
  } catch(error) {
    return false
  }
}
`

Is there a way to achievce this? I don't want it to retry if the healthcheck fails.

I appreciate the assistance

**Comment by balmacefa** [comment]
retryCondition is call is Axios return an Error

**Comment by balmacefa** [comment]
try this https://github.com/JustinBeckwith/retry-axios
