### ISSUE TITLE
Axios interceptors called incorrectly when using axios-retry

### ISSUE THREAD

**Issue by Nicvaniek** [softonic/axios-retry#199]
#### Bug description
When registering success and error response interceptors on the axios instance and axios-retry is used, failed retries cause the success interceptor to be called on retry instead of the error interceptor.

#### To Reproduce
Link to code sandbox: [Axios retry example](https://codesandbox.io/s/axios-retry-example-h7b4jj?file=/src/App.js)

Steps:
1. Open the console
2. Click on the "Make Error API Call" button and wait for the request to complete
3. The console shows that the error interceptor was correctly called on the first failure, but the success interceptor was incorrectly called for all 3 failed retries.
4. If the axios-retry portion on line 11 is commented out, the interceptors get called correctly.

![image](https://user-images.githubusercontent.com/14542853/168044961-a06616bf-abde-489e-a80b-d2dfc2b7085e.png)

#### Expected behavior
When a retry fails, it should call the error interceptor on the axios instance.

#### Environment
 - Axios Version 0.27.2
 - axios-retry Version 3.2.5

**Comment by JPStrydom** [comment]
We're also experiencing this issue

**Comment by mindhells** [comment]
Change your error interceptor to this:

```js
const errorInterceptor = (response) => {
  console.error("Error interceptor called");
  return Promise.reject(response);
};
```

**Comment by JPStrydom** [comment]
> Change your error interceptor to this:
> 
> ```js
> const errorInterceptor = (response) => {
>   console.error("Error interceptor called");
>   return Promise.reject(response);
> };
> ```

Would 
```
const errorInterceptor = (response) => {
  console.error("Error interceptor called");
  throw response; 
};
```
Achieve the same? 🤔

**Comment by mindhells** [comment]
> > Change your error interceptor to this:
> > ```js
> > const errorInterceptor = (response) => {
> >   console.error("Error interceptor called");
> >   return Promise.reject(response);
> > };
> > ```
> 
> Would
> 
> ```
> const errorInterceptor = (response) => {
>   console.error("Error interceptor called");
>   throw response; 
> };
> ```
> 
> Achieve the same? 🤔

I believe at least the success interceptor won't be called. Not sure if other registered error interceptors would be called though. You can try yourself using the example kindly provided by @Nicvaniek
