### ISSUE TITLE
No retries if a response is returned (even a 4xx or 5xx response)

### ISSUE THREAD

**Issue by elpete** [softonic/axios-retry#2]
A question before I do any work on a pull request.

In trying to use this library, I noticed that my requests weren't being retried at all.  It turns out that it was because they were returning a response as well, a 500 response.  [This line here](https://github.com/softonic/axios-retry/blob/master/es/index.js#L41) prevents retries in that case.

Would you be open to a pull request that addresses this issue?  I'm happy to do the work, but I'm not sure what would be the better solution, whether that would be removing that check all-together or adding a check for a different value (like status code) or something else.

**Comment by rubennorte** [comment]
The original goal of this package was to retry requests when there were network errors. Retrying requests when the server responds isn't always safe. We could consider a `isRetryAllowed: (error) => boolean` option to configure that behaviour and maintaining the current one as default.
