### ISSUE TITLE
Max number of retry

### ISSUE THREAD

**Issue by rainrisa** [softonic/axios-retry#207]
How much retries can we do? Can i set the number of retry to let's say 12000?

**Comment by gimyboya** [comment]
You can, but you most probably shouldn't. Depending on your scenario you don't want your app to run out of memory or the API you are calling to get overwhelmed by calls that even if they fail, will keep retrying for 12000 times.

**Comment by himanshufize** [comment]
@rainrisa I think 3 will be justified count and max 5 as there could be case of rate limit from API we using.

**Comment by mindhells** [comment]
I believe the question has been answered
