### ISSUE TITLE
ESM default import `This expression is not callable`

### ISSUE THREAD

**Issue by jdbruijn** [softonic/axios-retry#228]
I ran into this issue when trying to import this as default import. I'm not too familiar with manually created types and namespaces, so I'm not entirely sure what is going on. Please see my basic reproduction repo: https://github.com/jdbruijn/axios-retry-test. I did some tests and can get the import to work by casting the type, but that should not be needed of course. This is with `esModuleInterop` and v3.5.0.

<details><summary>System info</summary>
<p>

```
  System:
    OS: macOS 12.6.5
    CPU: (4) x64 Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz
    Memory: 78.21 MB / 8.00 GB
    Shell: 5.8.1 - /usr/local/bin/zsh
  Binaries:
    Node: 18.16.0 - /usr/local/opt/node@18/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 9.5.1 - /usr/local/opt/node@18/bin/npm
```

</p>
</details>

**Comment by erkannt** [comment]
Perhaps pertinent discussion: https://github.com/microsoft/TypeScript/issues/52086

**Comment by folkg** [comment]
I am seeing the same error on my project. I was able to work around it in the same way by using your type-casting solution.

**Comment by MLinek** [comment]
Using ts-ignore helped in my case

```typescript
import axiosRetry from "axios-retry";
// @ts-ignore
axiosRetry(axios, {retries: 3, retryDelay: axiosRetry.exponentialDelay});
```
