### ISSUE TITLE
Feature request: Handle async onRetry function

### ISSUE THREAD

**Issue by netanelep** [softonic/axios-retry#236]
Hi,

Can you add support for async onRetry functions?
Can I make a PR to make that happen?

One use case example is to refresh a token on 401

**Comment by matthewborgman** [comment]
@netanelep, per the docs, `onRetry` is "A callback to _notify_ when a retry is about to occur. Useful for tracing." and so async support isn't necessary.

`retryCondition`, however, does support `async` and it's been used to support logic like refreshing a token.

**Comment by mindhells** [comment]
this is added in 3.8.1
