### ISSUE TITLE
Something wrong with the timeout handling?

### ISSUE THREAD

**Issue by NemoAlex** [softonic/axios-retry#24]
In my case, I tried to make a client with 3s timeout:

```
var instance = axios.create({
  timeout: 3000
})
```

And apply a retry:

```
axiosRetry(instance, { retries: 2, retryCondition: () => true })
```

When I test it, the original request times out after 3s as normal, but after that, 2 retries fails immediately.

What I want is every request could wait 3 seconds. What should I do?

**Comment by rubennorte** [comment]
That isn't supported. This library is meant to work transparently so using the specified request timeout in every retry would increase the overall timeout considerably. You could do it with an additional interceptor that resets the timeout after axios-retry creates the retry request.

If you'll be willing to create a PR we can consider adding a `shouldResetTimeout` option that defaults to `false`.
