### ISSUE TITLE
What is the initial retry delay

### ISSUE THREAD

**Issue by Stevemoretz** [softonic/axios-retry#243]
Using Apollo's retry for instance you can define an initial retry time.

```jsx
        new RetryLink({
            delay: {
                initial: 1500,
            },
        }),
```

While this library, doesn't have that option at least it would be nice to mention what the initial time is by default adding an option to change it however would be awesome.

**Comment by yutak23** [comment]
According to README, the default `retryDelay` time is 0.

![image](https://github.com/softonic/axios-retry/assets/79501292/335b6014-699e-49cc-876f-0d42fe6da1e9)

So I think we need to implement the function as follows.

```js
axiosRetry(axios, { retryDelay: () => return 1500 });
```

> Just by skimming your code, it's probably 100ms?

Since it is an `Exponential Backoff`, I believe the Delay time is not constant but increases exponentially.
https://cloud.google.com/iot/docs/how-tos/exponential-backoff

**Comment by Stevemoretz** [comment]
> According to README, the default `retryDelay` time is 0.
> 
> ![image](https://user-images.githubusercontent.com/79501292/269169150-335b6014-699e-49cc-876f-0d42fe6da1e9.png)
> 
> So I think we need to implement the function as follows.
> 
> ```js
> axiosRetry(axios, { retryDelay: () => return 1500 });
> ```
> 
> > Just by skimming your code, it's probably 100ms?
> 
> Since it is an `Exponential Backoff`, I believe the Delay time is not constant but increases exponentially. https://cloud.google.com/iot/docs/how-tos/exponential-backoff

Thanks so much for the detailed explanation, and sorry I forgot to mention I was using the exponential, and using that the delay changes as you mentioned but what I was after was the initial delay for instance :

If the initial delay is 1s. The delays will be : 1s,2s,4s,...
If the initial delay is 2s. The delays will be :
2s,4s,8s,...

So essentially the initial delay is responsible for how slow or fast the retries happen.

**Comment by yutak23** [comment]
> If the initial delay is 1s. The delays will be : 1s,2s,4s,...
> If the initial delay is 2s. The delays will be :2s,4s,8s,...
>
> So essentially the initial delay is responsible for how slow or fast the retries happen.

If such behavior is desired, one answer seems to be to implement the following.

```js
const initialDelay = 2;

axiosRetry(axios, { retryDelay: (retryNumber) => return Math.pow(initialDelay, retryNumber) });
```

**Comment by Stevemoretz** [comment]
Makes sense closing :)
