### ISSUE TITLE
TypeError: axiosRetry is not a function in v4.0.0

### ISSUE THREAD

**Issue by nodegin** [softonic/axios-retry#259]
With latest 4.0.0 I got `TypeError: axiosRetry is not a function` for `import axiosRetry from 'axios-retry';` imports,
if I change to `import * as axiosRetry from 'axios-retry';` it seem can be imported but the typing will be broken:
```
This expression is not callable.
  Type 'typeof import("/Users/user/Desktop/project/node_modules/axios-retry/dist/cjs/index")' has no call signatures.
```

**Comment by mindhells** [comment]
can't reproduce this in a simple ESM (type="module") project
see https://stackblitz.com/edit/stackblitz-starters-dzcrb9?file=index.js
please provide an minimum example to reproduce the issue
Have in mind that, since 4.0, you need to use this method to import from CJS:
````js
// CommonJS
const axiosRetry = require('axios-retry').default;
````

**Comment by nodegin** [comment]
So it seem the issue is caused by the Node 21.3.0 release,
by explicitly setting the Node version to 21.2.0 in package.json
```
  "engines": {
    "node": "21.2.0"
  },
  ```
The build is working again in CI

**Comment by vivmagarwal** [comment]
const axios = require("axios").default works for CJS

**Comment by fredsensibill** [comment]
> I'm getting this error as well in unit tests in an ESM Typescript codebase using jest, ts-jest (and `NODE_OPTIONS=--experimental-vm-modules` set).

This is exactly my case. Type check succeeds if I run `tsc --noEmit` but my jest tests fail with `This expression is not callable`

**Comment by jeremysimmons** [comment]
This threw me off too. I would much prefer that the axios-retry CJS module behave similarly to axios.
I do not want to have to know about adding `.default` to the end of `require('axios-retry')`.

**Comment by ibqn** [comment]
> I created a minimal reproduction repo https://github.com/nodegin/axios-retry-v4-bug
> 
> You can try `npm install && npm run build` and you will see the bug I am using Vite SSR feature in my project
> 
> so it seem for CJS it expect default module export should be exported by just `module.exports` but in v4 case, the export is under `default` which breaks normal CJS imports

so how this minimal example should be fixed? I am still confused 🫤

**Comment by edsonboldrini** [comment]
I'm converting a project to esmodules and started importing async-retry like this and worked for me, but it's still very ugly: 

`import axiosRetry from '../../../node_modules/axios-retry/dist/esm/index.js';`

Also had to add it in my jest.config.ts to prevent errors `import outside a module`: 

```
{
  ...
  transformIgnorePatterns: ['node_modules/(?!(p-queue|p-timeout|axios-retry)/)'],
  ...
}
```

**Comment by nodegin** [comment]
Just an update to this issue, I switched to gaxios which provide retry functionality out of the box

**Comment by ahtokca** [comment]
I have the issue using `tsx` and tsconfig like below:
```{
  "compilerOptions": {
    "allowJs": true,
    "allowSyntheticDefaultImports": true,
    "composite": true,
    "declaration": true,
    "declarationMap": true,
    "emitDeclarationOnly": true,
    "emitDecoratorMetadata": false,
    "esModuleInterop": true,
    "experimentalDecorators": false,
    "forceConsistentCasingInFileNames": true,
    "importHelpers": true,
    "incremental": true,
    "isolatedModules": true,
    "lib": ["es2022"],
    "module": "ES2022",
    "moduleResolution": "bundler",
    "noEmitOnError": true,
    "noFallthroughCasesInSwitch": true,
    "noImplicitOverride": true,
    "noImplicitReturns": true,
    "noUnusedLocals": true,
    "pretty": true,
    "strictNullChecks": true,
    "removeComments": false,
    "resolveJsonModule": true,
    "skipDefaultLibCheck": false,
    "skipLibCheck": true,
    "sourceMap": false,
    "strict": true,
    "target": "es2022",
    "verbatimModuleSyntax": false
  }
}
```
