### ISSUE TITLE
Timeout should be preserved

### ISSUE THREAD

**Issue by ivoreis** [softonic/axios-retry#26]
I'm not exactly sure why we use a default timeout of 1ms, shouldn't the config.timeout be preserved if config.timeout > 0?

```js
// Minimum 1ms timeout (passing 0 or less to XHR means no timeout)
config.timeout = Math.max(config.timeout - lastRequestDuration, 1);
```

https://github.com/softonic/axios-retry/blob/e2fb34f0be38d3566be3aab565ed59ba97cb21af/es/index.js#L175

**Comment by modille** [comment]
See https://github.com/softonic/axios-retry/issues/24#issuecomment-333084181

And in the README now:

> Note: the plugin interprets the request timeout as a global value, so it is not used for each retry but for the whole request lifecycle.

So if you set a timeout of 10s and the request fails after 3s, then the retry will set the timeout to 7s (10s - 3s).

Personally, I think it'd make more sense to `reject()` whenever `config.timeout - lastRequestDuration < 1` rather then perform a retry with a 1ms timeout, but I haven't tried it out or investigated more deeply to see if there's any drawback to that.

**Comment by rubennorte** [comment]
The 1ms timeout is used to let Axios throw the timeout error, so we don't have to create a custom error that mimics the Axios one.
