### ISSUE TITLE
Provide option to trigger retry from successful (200) response in Axios's response interceptors

### ISSUE THREAD

**Issue by zhen-one** [softonic/axios-retry#267]
### Reason: 
Certain APIs consistently return a 200 HTTP code, with custom error codes embedded within the data payload

Like below
``` json
{
  "code": -1,
  "data":"...",
  "msg":"bad request"
}
```

Please add an option to decide whether to trigger retry from response or error.

``` javascript
axios.interceptors.response.use(function (response) {
    return response;
  }, function (error) {
    return Promise.reject(error);
  });
```

**Comment by obscurecat64** [comment]
@zhen-one you should be able to use the validateStatus function of axios together with retryCondition to accomplish this.

**Comment by obscurecat64** [comment]
> @zhen-one you should be able to use the validateStatus function of axios together with retryCondition to accomplish this.

apologies, in this case `validateStatus` is not enough. I've created a PR for this feature. Would like to hear your (or others') opinion on the usage (see: https://github.com/softonic/axios-retry/pull/272#issuecomment-2115781228) please 🙏

**Comment by mindhells** [comment]
this should be now covered by #272 thanks to @obscurecat64 
closing this issue
