### ISSUE TITLE
Missing export for isRetryableError()

### ISSUE THREAD

**Issue by Nudelsieb** [softonic/axios-retry#27]
This is needed inside `retryCondition` if one wants to retry for POST requests. The other exported error checks are not sufficient for this.

We could also think about adding a config object to override `SAFE_HTTP_METHODS` or use a separate constant. However, the export fix is easier and quicker.

**Comment by rubennorte** [comment]
Would you be willing to open a PR to fix it? ;)

**Comment by jlopezxs** [comment]
Fixed with #31
