### ISSUE TITLE
Axios-retry swallows the error response

### ISSUE THREAD

**Issue by lm-dlukmanov** [softonic/axios-retry#274]
Using axios-retry in NestJs app like this:
```
retryWrapper(this.client, {
            retryDelay: (retryCount) => {
                this.logger.log(`axios retry attempt № ${retryCount}`);
                return retryCount * +config.axios.retriesMultiplierMs;
            },
            retryCondition: (error) => {
                const errMessage = { errorData: error.response?.data || error };
                if (error.response?.config?.["axios-retry"]) {
                errMessage['axiosRetry'] = error.response.config["axios-retry"];
                }
                this.logger.error(`axios retry error: ${JSON.stringify(errMessage)}`);
                return !!error;
            },
            retries: +config.axios.retriesCounter,
        });
```

After the last retry as expected I should get an error:

```
try {
    someLogic();
} catch(err) {
    console.log(err) // And here is the error thrown after the last retry
}
```
The point is - the error thrown after last retry does not include all the information of the root error. I only get this structure: 
```
{
    message: "Request failed with status code 400", // as an example
    name: "AxiosError",
    config: "some stuff",
    code: "ERR_BAD_REQUEST",
    status: 400
}
```
whereas the root error have a lot of additional data in error response, i.e.: 

`{status: 400, {"errors":[{"code":"118","message":"MY_SERVICE service required for tariff MY_TARIFF"}]}}`

How can I get the whole error object not only some of the fields which are not very informative?

**Comment by yutak23** [comment]
would you try `console.log(err.response.data)`?

**Comment by lm-dlukmanov** [comment]
@yutak23  Yes. And I see there additional data. But when I catch error it doesn't have such field `response`

**Comment by lm-dlukmanov** [comment]
I decided to use interceptor of axios and handle it on my side.
