### ISSUE TITLE
Exponential delay has unnecessary final sleep

### ISSUE THREAD

**Issue by jakeleventhal** [softonic/axios-retry#275]
With exponential delay, the final sleep time is unnecessary. For instance if I have 5 retries and use the `exponentialDelay` function, after the final attempt, it still ends up sleeping even though it isn't going to try again.

**Comment by obscurecat64** [comment]
@jakeleventhal I tried to recreate your scenario but am unable to replicate your issue.

```
Started
[onRetry] retryCount 1
delay 208.30269580784702
[onRetry] retryCount 2
delay 415.23579640875306
[onRetry] retryCount 3
delay 867.6541979509457
[onRetry] retryCount 4
delay 1749.7805850471125
[onRetry] retryCount 5
delay 3552.4079582405384
performance.mark('start')
[maxRetryTimesExceeded] retryCount 5
performance.mark('end')
Delay after maxRetryTimesExceeded: 0.5896250009536743 milliseconds
.
```

from what i've tried, seems that after the final (fifth) attempt, `maxRetryTimesExceeded` is called without delay and the promise is rejected.

could you show some steps to reproduce the issue?

**Comment by jakeleventhal** [comment]
My mistake, i was mistaking "retries" for "total attempts"

**Comment by DawitAskabe** [comment]
@obscurecat64 can you share your test code? Wondering how you are logging the delay between the retries.
