### ISSUE TITLE
Exponential backoff?

### ISSUE THREAD

**Issue by chuckhacker** [softonic/axios-retry#3]
It's "good practices" to have exponential backoff for successive retries. Any plans to implement this?

**Comment by rubennorte** [comment]
We wrote this plugin just to retry network errors and we didn't expect to retry too many times, but that's a feature that could be added (together with #2).

Perhaps a `retryInterval` (that could be a number or a function that receives the request `config`) would be a good option to add. Would you consider creating a PR?

**Comment by TheChuckster** [comment]
Unfortunately, I realized a bit later that the environment that I am running my code in does not support JS promises (old version of SeaMonkey), sorry.

Once I fix this, sure, but right now upgrading things is a "nice to have" for us.

**Comment by antony** [comment]
I'm also looking for exponential backoff, but even a simple way to control the retry timeout would be useful.

My suggestion is to have two configuration methods:

Simple config
```javascript
retry: {
  attempts: 5,
  delay: 1000
}
```

or a function, to allow exponential backoff.

returning `-1` means don't retry
returning `1000 * attempt` means that on attempt 5, the retry delay is 5 seconds.
```javascript
retry: (attempt) => {
  if (attempt > 5) { return -1 }
  return 1000 * attempt
}
```

**Comment by TheChuckster** [comment]
I'm back, working on this.

**Comment by s3rious** [comment]
Well, I've basically just implemented this in my fork: https://github.com/s3rious/axios-retry/blob/master/es/index.js#L116

Config now receives 3 arguments, I've added `delay`, which can be a simple number or a function who receives an attempt count and should return number.

If Somme will help with tests and `README.md` I think we can make it a PR.

**Comment by towfiqi** [comment]
@s3rious Just replaced the `es/index.js` with your one and then tried like this but there was no delay `axiosRetry(axios, { retries: 3,delay : 11000 });`

**Comment by yipcma** [comment]
interested in exponential delay as well

**Comment by s3rious** [comment]
@towfiqi That's strange, have you rebuilt the lib after making changes?
I've just started a simple project with my fork, here is a [gist](https://gist.github.com/s3rious/506dd37c6de0ae3577a12e515ed1541c), and delay [works ok](http://take.ms/7tXGW).

**Comment by gregorym** [comment]
What is the progress on this?
@towfiqi Looking at your code this is not exponential backoff, it is linear since I can only pass a number.

delay should accept a number or a function so anyone can customize their delay logic.

**Comment by matthiasfeist** [comment]
Is there any progress on that?

**Comment by rubennorte** [comment]
@moose56 is working on it in #28

**Comment by matthiasfeist** [comment]
Sorry I must have missed that there is a PR open... Thanks!

**Comment by dashmug** [comment]
This is great.
