### ISSUE TITLE
Custom `retryDelay` function with additional optional params are incorrectly executed

### ISSUE THREAD

**Issue by thatmarvin** [softonic/axios-retry#34]
In https://github.com/softonic/axios-retry/blob/v3.0.2/es/index.js#L195, `retryDelay` is passed in `error` as the second arg, but doesn't look like `error` actually used?

This is a problem when I pass in a custom `retryDelay` function that looks like this:

```js
function customBackoff(
  retryNumber = 0,
  firstInterval?: number = 1000,
  maxInterval?: number = 5 * 60 * 1000) {
  // …
}

axiosRetry(axios, {
  retryDelay: customBackoff
});
```

So when `retryDelay` gets called, `firstInterval` incorrectly becomes the error object.

**Comment by mawrkus** [comment]
Hi!
It looks like your `customBackoff(retryNumber, firstInterval, maxInterval)` function doesn't follow the same signature as `retryDelay(retryCount, error)`.  Maybe you could do something like:
``
function retryDelayFactory(firstInterval ? : number = 1000, maxInterval ? : number = 5 * 60 * 1000) {
  return function retryDelay(retryCount, error) {
    // …
  };
}

axiosRetry(axios, {
  retryDelay: retryDelayFactory(3000, 5*60*3000)
});
``

**Comment by thatmarvin** [comment]
Ah just realized that the args are actually documented, I just totally missed it cos I was referencing the implementation directly. So it's all good, thanks!
