### ISSUE TITLE
Is there a way to plug into the retry process to display feedback to user?

### ISSUE THREAD

**Issue by anagrath** [softonic/axios-retry#35]
Hi,

I love this.  I'm starting to think about the failure scenario, and what I was thinking was after the first request fails (or maybe the second or third), I'd like to display a dialog box informing the user that we are having some network issues and we are retrying... to change on final error to asking them to check their internet connection.  

We want that because we are using axios on mobile through cordova/webviews and if the signal is bad, it is just good to let the user know that we are trying the best we can.  We set it up for 10 retries with exponential decay and we've tested using chrome by flipping the connection off and on where requests would be happening and it is working wonderfully... 

Any help or guidance appreciated.

It would be really nice to have a callback function when retry occurs so that the UI can respond.

**Comment by mawrkus** [comment]
Hi!

Have you tried:

``
function retryDelay(retryNumber = 0) {
  displayRetryMessage();
  const delay = Math.pow(2, retryNumber) * 100;
  const randomSum = delay * 0.2 * Math.random(); // 0-20% of the delay
  return delay + randomSum;
};

function displayRetryMessage(retryNumber) {
  if (retryNumber > 1) return;
  alert('Ooops! We are having some network issues & we are retrying. Thanks for being patient!');
}

axiosRetry(axios, { retryDelay });
``

**Comment by anagrath** [comment]
Had not thought of that. After I read the code I forked and added it.  Would you mind seeing the PR? It is a little cleaner than doing what you recommend and I am happy either way if you say go this route... though reimplementing the exponential decay backoff is what I was trying to avoid. 

Best

**Comment by anagrath** [comment]
I think it makes sense.  I will reimplement today and if it is working I will kill my fork and PR. 

Though, we should at least update the documentation… that is darn confusing to use the delay function for callback :).
