### ISSUE TITLE
New option to also retry on timeout

### ISSUE THREAD

**Issue by ValentinH** [softonic/axios-retry#39]
Thanks for this great package.

Would you accept a PR adding an option to also retry on timeouts?

I understand that we can override the  `retryCondition` with custom logic. However, I ended up copying the `isRetryableError`, `isIdempotentRequestError` and `isNetworkOrIdempotentRequestError` in my code just for removing the checks about `error.code !== 'ECONNABORTED'`. This doesn't feel right.

**Comment by rubennorte** [comment]
You could do this without copying the functions:

```javascript
isRetryableError: error => isNetworkOrIdempotentRequestError(error) || error.code === 'ECONNABORTED'
```

**Comment by ValentinH** [comment]
I'm not sure this would work because for example this would retry on a timeout on a POST request (idempotent criteria).

**Comment by jlopezxs** [comment]
Added `shouldResetTimeout`. Thanks to @yns01 !

**Comment by ValentinH** [comment]
Actually, this is a related topic but not exactly what I was suggesting to contribute.

`shouldResetTimeout` defines if the timeout should be reset between retries.
`retryOnTimeout` would also retry when a call timeouts (which is not the case today due to [this check](https://github.com/softonic/axios-retry/blob/master/es/index.js#L24)).
