### ISSUE TITLE
Need maintainers?

### ISSUE THREAD

**Issue by yns01** [softonic/axios-retry#45]
Hey @rubennorte @jlopezxs , 

I was wondering if you were looking for any maintainer? I'm actively using axios-retry and I would be ready to maintain the repository.

**Comment by jlopezxs** [comment]
Hi @yns01,
I will talk with the coworkers because the package is part of the group of the company.

Thank you!

**Comment by yns01** [comment]
Thanks @jlopezxs !

Not related, but I did not feel a issue is needed; do you mind publishing a new version of the package to include the latests commits?

**Comment by jlopezxs** [comment]
Update to 3.1.0!

**Comment by yns01** [comment]
Thanks @jlopezxs for the invitation!
