### ISSUE TITLE
Why axios-retry config didn't lose?

### ISSUE THREAD

**Issue by zgayjjf** [softonic/axios-retry#55]
Hello there,

Axios-retry is a excellent lib. 
I'm reading it's code, and there is something I don't understand. 

According to the code [here](https://github.com/axios/axios/blob/master/lib/core/Axios.js#L36) and [here](https://github.com/axios/axios/blob/master/lib/core/mergeConfig.js), Axios will only merge some predefined attributes on config, which means axios-retry config will get lost.

However, axios-retry works just fine, and config didn't lose.

This makes me confused, and I can't figure out why is that.

Any help will be appreciated.

**Comment by mawrkus** [comment]
If I understand correctly your question, the answer is here https://github.com/axios/axios/blob/master/lib/core/Axios.js#L37

All the properties of config object are merged, not only predefined ones.
This allows axios-retry to add its own internal config here https://github.com/softonic/axios-retry/blob/master/es/index.js#L89

Hope this helps.

**Comment by zgayjjf** [comment]
@mawrkus Thanks for the reply.

I figured it out.

Axios-retry never extends Axios's default config. It uses interceptors to add its config before every request is sent. 

https://github.com/softonic/axios-retry/blob/master/es/index.js#L175

This explains everything.

> BTW, Axios doesn't merge properties that are not predefined.
