### ISSUE TITLE
How does this work with Refresh Tokens?

### ISSUE THREAD

**Issue by chobo2** [softonic/axios-retry#56]
Hi

I am wondering how axios-retry figures out when to try again? I have a site that will have refresh tokens, so if a request fails it might be just as simple as getting a new "access token".

How can Axios to basically say if the first request failed, look if it is a 401 error and if so get a new token and then try again.

**Comment by yns01** [comment]
Hey @chobo2, you can easily provide your own retry condition via the `retryCondition` parameter

**Comment by chobo2** [comment]
@yns01 

I will have to look in more detail, but how I setup my axios right now, I am using interceptor on response, if a 401 comes back, it will automatically through the interceptor send the refresh token and if successful  it will resend the original request.

How would axios-retry and the interceptor place nice together, so axios-retry would only resend if the interceptor was able to re authenticate the user?

I don't want to have to put the same authentication code in every axios call.

**Comment by falstack** [comment]
I have same question

**Comment by chobo2** [comment]
@falstack 

I never figured out how to do this and sort of moved away from all this. The one problem I found with interceptors was if you got a page and you got like 5 ajax requests firing at once. 

If the token is expired then the request will fail and the access token will be sent but if you got like 5 of them firing all at the same time they all might try to send the 1 access token back which after the 1st request would be deleted, and thus the rest of my requests would fail as they could not find the access token and thus my front end code would logged them out.

You would need some sort of queuing or something like that to make it work, I just decided to switch  a timer.

If my token expires after 20 mins, I set a timer for 19 mins to just get a new token and access token.

**Comment by falstack** [comment]
@chobo2 timer（setInterval） maybe is a good idea，thanks！

**Comment by chobo2** [comment]
> @chobo2 timer（setInterval） maybe is a good idea，thanks！

Yep use setInterval not setTimeout like I did my accident  the first time around and was wondering why it did not refresh after the first time.

**Comment by oferRounds** [comment]
@mawrkus following this question, one possible solution would be hold all retries until we manually say it’s ok now  (i.e., the token was refreshed) (by invoking a method). Is there some way to do this?

**Comment by nwaughachukwuma** [comment]
> Hey @chobo2, you can easily provide your own retry condition via the `retryCondition` parameter

@yns01 it doesn't appear `retryCondition` can handle an async request. Any idea how to go about this?
