### ISSUE TITLE
Release new version with updated index.d.ts file

### ISSUE THREAD

**Issue by mattwexa** [softonic/axios-retry#58]
Hi,

I noticed that a few functions are missing from `index.d.ts` in the latest released version (issue #52), and I see that this has been fixed in `master` (PR #54). Would it be possible to release a new version with this fix?

Thanks!

**Comment by adriantombu** [comment]
Same problem here 😁

**Comment by ak5** [comment]
+1 for `axiosRetry.exponentialDelay`

**Comment by mattwexa** [comment]
Pinging @jlopezxs from @softonic who appears to be maintaining this package: could you please release a new version with the fixed index.d.ts file?

**Comment by yns01** [comment]
@jlopezxs Could you please do a release?

**Comment by bmakuh** [comment]
+1 on this. As a workaround, you can do `"axios-retry": "softonic/axios-retry#40e3f07"` in your package.json

**Comment by lawloretienne** [comment]
> "axios-retry": "softonic/axios-retry#40e3f07"

I get the following error
src/index.ts(44,49): error TS2339: Property 'exponentialDelay' does not exist on type 'IAxiosRetry'.

event when i tried your workaround @bmakuh.

@mattwexa What is the status on this issue?

**Comment by mattwexa** [comment]
@lawloretienne basically the issue is already solved on master, we're just waiting for a release by the maintainer of this package. Could somebody from @softonic-auto please answer? If you are not maintaining this package anymore, could you please let us know? cc @bvis @ivanmp91 @jeurrutia @jlopezxs @superruzafa

**Comment by adriantombu** [comment]
If you need someone to help maintain the package, I'll be glad to give you a hand on that 👍

**Comment by chatoo2412** [comment]
[Workaround](https://stackoverflow.com/a/40326719)

> ```jsonc
> /// tsconfig.json
> 
> "paths": {
>   "*": ["my-custom-types/*", "*"]
> }
> ```

**Comment by mawrkus** [comment]
Hi everyone,
Sorry for the delay, we'll be looking at this asap!

**Comment by mattwexa** [comment]
Awesome thanks @mawrkus! I updated to the latest version, the typings work as expected. I guess you can close the issue now :)

**Comment by mattwexa** [comment]
Actually I opened this issue, I'll close it 😃
