### ISSUE TITLE
retryDelay should accept number or function

### ISSUE THREAD

**Issue by probil** [softonic/axios-retry#62]
Hi, guys

Thanks for you library. 👍 
I have a question. What is the reason behind passing `retryDelay` as a function? In vast majority of cases we use plain numbers and we have to wrap this numbers to functions all the time.

It would be nice if we can pass number or function to `retryDelay`
As it will:
- improve readability
- simplify the code
- allow us to store configuration in json

**Comment by mawrkus** [comment]
Because a function is a simple yet powerful abstraction ;)
It can help you scheduling the retries (e.g. exponential backoff, a standard error handling strategy for network applications), while still providing you a way to return a fixed number.
The best of both worlds.
