### ISSUE TITLE
update timeout value when retrying 

### ISSUE THREAD

**Issue by kushbhandari** [softonic/axios-retry#64]
Is it possible to update timeout value (no reset) when retrying first time and update again when retrying second time and so on ?

**Comment by drwharris** [comment]
Yes you can. The main readme details this :

// Custom retry delay
axiosRetry(axios, { retryDelay: (retryCount) => {
  return retryCount * 1000;
}});

**Comment by mawrkus** [comment]
Looks like this is going to be the default behaviour with Axios 0.19.x
We are currently working on supporting it.

**Comment by redredredredredred** [comment]
I simply skipped over the problem, hoping it would be helpful
```
let retries = 0
axiosRetry(axios, {
    retries: 3,
    retryCondition:(error)=>{
      let config = error.config;
      if (!config) {
        return false;
      }
      retries = retries + 1
      if(retries>= 3){
        retries = 0
        return false
      }
      return true
      
      // do something 
      // axiosRetry.isNetworkError
      // axiosRetry.isRetryableError
      //axiosRetry.isSafeRequestError
      // axiosRetry.isIdempotentRequestError
      // axiosRetry.isNetworkOrIdempotentRequestError
      // axiosRetry.exponentialDelay
    }
  });
```

**Comment by mawrkus** [comment]
All good if it works for your use case!
