### ISSUE TITLE
Can we have a UMD version of this on CDN somewhere please?

### ISSUE THREAD

**Issue by rosdi** [softonic/axios-retry#71]
I tried to create my own using rollup but the build fails... perhaps an 'official' umd version would be nice?

**Comment by rosdi** [comment]
I have successfully use rollup to build umd, cjs, and esm versions... will publish later once I figured out how to integrate this with the existing tests/build scripts.

**Comment by rosdi** [comment]
The fork (with umd built) is here in case anyone is interested: https://github.com/rosdi/axios-retry

Haven't integrate with the tests yet though...

**Comment by mawrkus** [comment]
Hi!
Sorry for the late reply. We are considering to use [microbundle](https://www.npmjs.com/package/microbundle) but unfortunately it's not our priority for now. If you're eager to move this, we would definitively consider a PR :)
