### ISSUE TITLE
Force retry on 200 and when condition is met

### ISSUE THREAD

**Issue by KayHS** [softonic/axios-retry#74]
I am short polling an endpoint until some data is ready i would like to retry the request up to 10 times.

> When the data is not ready i recieve a 200 with an empty array.
> 
> When the data is ready i recieve a 200 with a non-empty array.

I use the following libraries 
https://github.com/axios/axios
https://github.com/softonic/axios-retry

     try {
    
       const axiosInstance = axios.create();
    
       axiosInstance.interceptors.response.use((response) => {
    
         if (response.data.metrics.length === 0) {
           const error = new Error("Metrics Not Ready");
           return Promise.reject(error);
    
         }
         return response;
       }, (error) => {
         return Promise.reject(error);
       });
    
       axiosRetry(axiosInstance, {
         retries: 10,
         retryCondition: (error) => {
           console.log("RETRY CONDITION", error);
         },
       });
    
       const metrics = await axiosInstance(options);
    
     } catch (error) {
       console.log(error);
     }

I have created an axios interceptor to check the length of the array if its 0 i am throwing an error. However this does not get caught by axiosRetry which at this point i want to retry the request. Instead it is being caught in the try catch block and ends.

is there some way i can force axiosRetry to retry by overwriting the response in the interceptor when a condition is met?

**Comment by KayHS** [comment]
Even if i override the response status code to something axiosRetry should pick up. The request is not being retried.

```
      axiosInstance.interceptors.response.use((response) => {
               if (response.data.metrics.length === 0) {
                    response.status = 500;
                }
                return response;
            }, (error) => {
                    return Promise.reject(error);
                });

            axiosRetry(axiosInstance, {
                retries: 10,
                retryCondition: (error) => {
                    return error.response.status === 500;
                },
                retryDelay: (retryCount: number) => {
                    return retryCount * 1000;
                },

            });

            const metrics = await axiosInstance(options);
```

**Comment by drwharris** [comment]
Its not particularly well documented but the issue is that retryCondition needs to return true if you wish to retry or false if you dont. So in your instance, you would want to return true if the length of the body is 0.

**Comment by darrylmabini** [comment]
@mawrkus did you solve the issue? I'm having the same problem. And looking at the axios-retry code this is not possible becaiuse it will only execute if the status codes falls outside the range of 2xx.

https://github.com/softonic/axios-retry/blob/9dd59fb628164bf757144db66487dd5496eb32db/es/index.js#L180

**Comment by eduhh94** [comment]
@darrylmabini do the following:

axiosInstance.interceptors.response.use(
  function (response) {
    // Any status code that lie within the range of 2xx cause this function to trigger
    // Do something with response data
    if (response.data.metrics.length === 0) {
      response.status = 500;
      throw response;
    }

    return response;
  },
  function (error) {
    console.log('intercepted error: ', error);
    return error;
  }
);
