### ISSUE TITLE
How can we check if the axios-retry is retrying the axios call ? 

### ISSUE THREAD

**Issue by Tri-Vi** [softonic/axios-retry#79]
**Question:**

1. Is there anyway that we can check or get feedback when axios-retry is retrying the axios call ?

**Comment by drwharris** [comment]
I do this:

>        let instance = axios.create(
>            {
>                timeout: 30000
>            }
>        );
>
>        axiosRetry(instance, {
>            retries: 10, retryDelay: (retryCount: any) => {
>                let interval = 500 * retryCount;
>                Logger.warning(`Error: Retry #${retryCount} will occur after ${interval}ms`);
>                return interval;
>            }
>        });
>
>        await instance.get(url) ... etc

**Comment by Tri-Vi** [comment]
@drwharris : Thanks. I'll give it a try
