### ISSUE TITLE
retryCount not incremented when using custom retryCondition

### ISSUE THREAD

**Issue by drwharris** [softonic/axios-retry#80]
I am trying to get retry to work with a 429 error on a POST. By default a 429 is not a network error and POST is not an IDEMPOTENT method so its considered a "success" by "axios-retry".

I have therefore implemented the following:

```
let loader = Axios.create({
    timeout: 3600000, // 1 Hour to account for incremental retries
});

AxiosRetry(loader, {
    retries: 10, retryDelay: (retryCount) => {
        let interval = 60000 * retryCount;
        console.log(`Loader request failed. Attempt #${retryCount} will occur after ${interval}ms`);
        return interval;
    }, retryCondition: (error) => {
        return AxiosRetry.isNetworkOrIdempotentRequestError(error) || error.response.status == "429";
    }
});

let content = { api_key: account.apikey, client_name: account.name };
loader.post(url, content, { headers: { 'Content-Type': 'application/json' } })
    .then(function (response) {
        resolve();
    })
    .catch(function (error) {
        reject(error);
    });
```

This works fine in terms of retrying on a 429 error (or Network, etc) but when the retryDelay function is called, retryCount is always 1 so I get the message "Loader request failed. Attempt #1 will occur after 60000ms" every time. 

How do I get the retryCount to increment properly? Is my mechanism to deal with the 429 correct?

**Comment by mawrkus** [comment]
My guess is that your `retryCondition` should check for a 429 status as a number: 

`error.response.status === 429`

**Comment by drwharris** [comment]
Ill give it a go but if retryCondition fails, it wont even get into retryDelay so not sure how that will help. To be clear, the issue is that when I am in the retryDelay callback, retryCount is never incremented.

To me the issue is that the logic to increment retryCount is caught up in the default retryCondition callback and is not called when a custom callback is used.

**Comment by danielmcq** [comment]
I have been seeing issues where neither retry count or retry delay are respected. I had upgraded to axios 0.19.0 within the last week, so I suspected that. Sure enough, when I downgraded back to 0.18.0, the axios-retry went back to working as it should. I will try to file a bug report later for this incompatibility where I can properly display the evidence.

**Comment by mawrkus** [comment]
Could what you describe be a duplicate of #59 ?

**Comment by danielmcq** [comment]
@mawrkus Yep, I think you’re right. I didn’t realize the problem would have shown up that long ago in the beta of axios 0.19.0.

@drwharris, can you confirm which version of axios you are using?

**Comment by drwharris** [comment]
@danielmcq @mawrkus 
COnfirming I was on 0.19. Downgraded to 0.18.1 and its working. And yes, this is exactly the same as #59. Sorry, poor form on my behalf there. Ill close this as you're actively working on that issue.
