### ISSUE TITLE
Hang on network error

### ISSUE THREAD

**Issue by broom9** [softonic/axios-retry#89]
With the following codes, if the network address is unreachable (e.g. when accidentally set as undefined or some other network issues), the script hangs without throwing errors.

```
const axios = require('axios');
const axiosRetry = require('axios-retry');

axiosRetry(axios, {
  retries: 3,
  retryDelay: axiosRetry.exponentialDelay,
  retryCondition: error => axiosRetry.isNetworkOrIdempotentRequestError(error)
    || (error.response && error.response.status === 429),
});


axios.get('undefined/v1').then(() => {
  console.info('Successful');
}).catch((e) => {
  console.error(e);
});
```

axios-retry: 3.1.2
axios: 0.19.0

**Comment by hpurmann** [comment]
We're facing the same problem. It never throws an error, just hangs

**Comment by cjancsar** [comment]
With the feedback logic from https://github.com/softonic/axios-retry/issues/35 you can see that the `retries` variable seems to be ignored, and it will just perpetually retry!

**Comment by MaksimKiselev** [comment]
Since version 0.19.0 axios filter out custom properties in config , see https://github.com/axios/axios/issues/164#issuecomment-524756674

Workaround for this issue - downgrade to axios `^0.18.0`

**Comment by mawrkus** [comment]
https://github.com/softonic/axios-retry/issues/59
