### ISSUE TITLE
Backup URL?

### ISSUE THREAD

**Issue by jakubgawlikowski** [softonic/axios-retry#90]
Is it possible to configure a backup URL for retry attempts?

**Comment by mawrkus** [comment]
Can you elaborate? What's your use case?

**Comment by mawrkus** [comment]
Closed for inactivity, feel free to re-open it if needed.

**Comment by IlyaSemenov** [comment]
I will second this request. As I see it, I want to provide the list of URLs, and axios-retry will iterate over it when making retries.

My specific use case would be:
* I provide `https://api.myproject.com` as the base URL
* I also provide `https://api-myproject.mycompany.com` as the backup base URL

It's been not once that the owners of `myproject.com` messed with DNS or forgot to renew the domain on time. A backup URL would prevent a client (such as a react-native app talking with the API server with Axios) from breaking.

**Comment by amiralitaheri** [comment]
@mawrkus Any update on this feature?
