### ISSUE TITLE
Retry on CORS error

### ISSUE THREAD

**Issue by Zyles** [softonic/axios-retry#96]
When I get a CORS or network error it does not seem to retry properly for me.

**Comment by pixagraphic** [comment]
Same for me. Altought I noticed that a GET Request will be retried, however POST requests that result in CORS errors will not be retried.

**Comment by mawrkus** [comment]
Why would you retry on CORS error? The server should be configured adequately to allow your requests or you should use JSONP, if possible.

**Comment by Zyles** [comment]
> Why would you retry on CORS error? The server should be configured adequately to allow your requests or you should use JSONP, if possible.

I don't own the server.

- Server failures
- Cache hit failures
- Network failures

**Comment by mawrkus** [comment]
Ok, feel free to open a proper issue with more details (Axios version, use case, response from the server and any relevant info).
